export const timeline = {
  drawer: {
    label: 'Update',
    description:
      'The timeline shows notable events from every game day and is generated by AI from session summaries. Newly completed sessions are added automatically overnight; you can also update it manually here, including for older sessions.',
    update: 'Update timeline',
    updating: 'Updating...',
    pendingSessions: {
      one: '1 session without current events',
      other: '{formattedCount} sessions without current events',
    },
  },
  empty: {
    title: 'No timeline events yet.',
    adminHelp: 'Open “Update” in the side drawer to generate events for the sessions so far.',
    filtered: 'No events in the selected chapter.',
  },
  links: {
    session: 'Session',
    diary: 'Diary',
    diaryByUser: 'Diary by {name}',
    openDiary: 'Open diary',
  },
  events: {
    moreOnDay: 'More events on this day',
    panGesture: 'Mouse wheel / swipe',
    panAction: 'Move through the timeline',
    zoomGesture: 'Ctrl+mouse wheel / two fingers',
    zoomAction: 'Zoom: expand sub-events',
    clickGesture: 'Click',
    clickAction: 'Open details',
    day: 'Day {day}',
    current: 'current',
    clickForDetails: 'Click for details',
    noScenes: 'No sub-events recorded.',
    moreEvents: 'More events: {titles}',
    eventDetails: 'Event details: {title}',
  },
  status: {
    modelLoading: 'Loading the AI model...',
    working: 'AI is working on the timeline...',
    extracting: 'Extracting events...',
    almostDone: 'Almost done...',
    alreadyCurrent: 'The timeline is already up to date.',
    processingSession: 'Processing session “{name}” ({current}/{total})...',
    completed: 'Timeline update completed.',
  },
  notifications: {
    updated: 'Timeline updated.',
  },
} as const;
